### ISSUE TITLE
playlist reload frequency on live HLS stream excessive

### ISSUE THREAD

**Issue by gmarzot** [Blazemeter/HLSPlugin#7] opened 2020-02-29 18:11 UTC
I see the release note about aiming to comply with RFC guidance (half target duration i presume). however I am still seeing the playlist loaded many times a second where the target duration is several seconds.

3.0 version of plugin
5.2.1 jmeter
java 11 LTS

**Comment by rabelenda** [comment] 2020-02-29 19:43
Hello, thank you to put in contact. I am sorry to hear you are experiencing unexpected behavior.

Can you provide the URL of the master playlist to verify? If the URL is private in some sense, then can you provide the contents of the m3u8 of the master and media playlist files? It would be helpful to get the debug logs of jmeter as well if you can provide them. 

If you have any doubts, questions or comments, let us know.

Regards

**Comment by gmarzot** [comment] 2020-02-29 20:08
https://teststream.ramp.com/ramptv/loop.m3u8

i would expect a playlist get about every 2.5 sec.

thanks for the very quick reply. I can test new version if that helps

curl https://teststream.ramp.com/ramptv/loop.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:17987950
#EXT-X-DISCONTINUITY-SEQUENCE:149899
#EXTINF:3
video/stream-12072016/0500026413_player.hls-500k.split.70.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.71.ts
#EXTINF:5
video/stream-12072016/0500026413_player.hls-500k.split.72.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.73.ts
#EXTINF:3
video/stream-12072016/0500026413_player.hls-500k.split.74.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.75.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.76.ts
#EXTINF:3
video/stream-12072016/0500026413_player.hls-500k.split.77.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.78.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.79.ts
#EXTINF:3
video/stream-12072016/0500026413_player.hls-500k.split.80.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.81.ts
#EXTINF:6
video/stream-12072016/0500026413_player.hls-500k.split.82.ts
g

**Comment by rabelenda** [comment] 2020-02-29 21:10
Thank you, we will check on it and let you know what we find.

Regards

**Comment by rabelenda** [comment] 2020-03-02 20:30
We identified the root cause of the bug: it is related to interrupting a test and then starting a new one in the same JMeter instance. Can you verify that starting a fresh jmeter instance and not interrupting a plan the playlist reload times are properly working?

We are already working on fixing the above issue. If that is the issue you are experiencing then following release of the plugin should contain the fix. In the meantime, if you interrupt a test, you will need to restart jmeter for playlist reload times to work properly. 

Sorry for the inconveniences, and thank you for reporting this bug.

**Comment by gmarzot** [comment] 2020-03-02 21:11
yes - that is in keeping with what i was observing. I discovered that
starting the jmeter session over for each run and the issue did not appear.
I am seeing a playlist load at a proportional frequency to segment load -
more or less 1-to-1. this is fine.

**Comment by RicardoPoleo** [comment] 2020-04-02 19:17
Hello @gmarzot! Sorry for our delayed answer. Hope you are doing amazing!

This issue was fixed in our last release. Please take a look at our [release page](https://github.com/Blazemeter/HLSPlugin/releases)and try it out!

I'm closing this issue and, if you have any problem, please don't hesitate to write us back.

See you soon, and have a great day.

**Closed by RicardoPoleo** 2020-04-02 19:17 UTC
