### ISSUE TITLE
The plugin hangs the Jmeter

### ISSUE THREAD

**Issue by qchroman** [Blazemeter/HLSPlugin#24] opened 2021-06-08 11:45 UTC
Hello all,

I have noticed that the plugin hangs the Jmeter. The case is very simple, you need to point the Jmeter to the HLS stream and select the infinite loop count. The summary report shows that the plugin downloads all fragments and stops. When you click the STOP to stop the test, the jmeter fails to do so show the following in logs

```
2021-06-08 11:41:09,011 ERROR o.a.j.u.JMeterUtils: One or more test threads won't exit; see log file.
```

The version of jmeter used is 5.4.1. The version of bzm plugin is 3.1.

P.S. there is no such issue with DASH.

**Comment by RicardoPoleo** [comment] 2021-08-30 18:22
Hello @qchroman,

That's odd. We will review it on our end and come back to you after.

It is possible you share a link that let us test with your particular stream or your settings?

At any rate, I'll tag it as a bug and add it to our backlog to tackle it whenever possible.

Thanks for taking the time to report it.

Cheers!

**Comment by diego-ferrand** [comment] 2022-09-27 18:31
Hey @qchroman, we just launched a pre-release which includes improvments to the performance of the plugin. Try it out and let us know if this is still happening to you.

**Comment by qchroman** [comment] 2022-09-27 18:49
Hello @diego-ferrand , thank you for letting me know. Unfortunately, we've moved to a different tool so I won't be able to confirm the fix.

**Comment by diego-ferrand** [comment] 2022-09-28 16:20
Ok @qchroman , thanks for lettings us know!

I'm closing the issue since we can't reproduce it.

**Closed by diego-ferrand** 2022-09-28 16:20 UTC
Labels: bug
