### ISSUE TITLE
error if we set the duraton of the video playback

### ISSUE THREAD

**Issue by facsiaginsa** [Blazemeter/HLSPlugin#3] opened 2019-07-08 04:18 UTC
hello, i set the duration of the video (120 s), i get this error: 
![Capture](https://user-images.githubusercontent.com/20637480/60782687-e4972d80-a171-11e9-956d-b3c225e790c8.JPG)

when i set the duration to "whole video", it wont stop. The video duration is 11m, but it still run when the time show 13m+. why is it happen?

**Comment by rabelenda** [comment] 2019-07-08 19:50
Hello, thank you for reporting the issue. 

Can you provide the jmeter logs to be able to better trace the cause of the issue?

Regards

**Comment by facsiaginsa** [comment] 2019-07-10 02:03
Thanks for the respond.

Here is the log, i just use 2 thread, set the video duration by 600. i also attach my jmx for consideration, maybe my jmx config is wrong. 

[jmeter.log](https://github.com/Blazemeter/HLSPlugin/files/3375440/jmeter.log)

[hlssampler.zip](https://github.com/Blazemeter/HLSPlugin/files/3375447/hlssampler.zip)

**Comment by rabelenda** [comment] 2019-07-10 15:28
Hello,

The issue seems to be related with the plugin not properly resolving the url of the fragments and getting 404 response from the HLS server. Additionally, when such issue happen, it seems the plugin is not finishing since it can't download any fragments. 

Can you verify if the reported segments urls are ok (maybe using curl to see if you get 404 for the url, or since you are using a local server maybe you know what is the expected segment url), and if you can please share the contents of the master list and playlist (the response body in jmeter for the sample results you see in green)? Have you tried consuming the hls video from a browser? you can compare the requests to the server by checking with inspect in the browser the requests for the segments and check if they look the same as jmeter plugin.

Regards.

**Comment by facsiaginsa** [comment] 2019-07-11 09:24
**If you can please share the contents of the master list and playlist (the response body in jmeter for the sample results you see in green)?**
i'm afraid i don't understand what you mean, but i will send several screen shoot, maybe this is what you need. please let me know if i'm wrong

**Have you tried consuming the hls video from a browser?**
I use vlc and use network stream to consume the video. and it is alright. If I use my browser (chrome) the content is downloaded, not played on the browser. it can only played on browser if the browser is safari. and i dont use mac. hehe..

![Capture](https://user-images.githubusercontent.com/20637480/61039004-2f29db80-a3f8-11e9-9286-76979cdaaca2.JPG)
![Capture1](https://user-images.githubusercontent.com/20637480/61039006-2fc27200-a3f8-11e9-8725-cba4b870abb5.JPG)
![Capture2](https://user-images.githubusercontent.com/20637480/61039012-318c3580-a3f8-11e9-9446-41bb86d61a8e.JPG)

**Comment by rabelenda** [comment] 2019-07-12 18:39
Hello, from those three screenshots, can you send the same but showing the response and request tabs? Regards

**Comment by facsiaginsa** [comment] 2019-07-14 10:01
ok, tomorrow i will send it to you. Thx! 👍

**Comment by facsiaginsa** [comment] 2019-07-15 02:03
hi, here i send you the capture of response & request tab
[capture.zip](https://github.com/Blazemeter/HLSPlugin/files/3390661/capture.zip)

**Comment by rabelenda** [comment] 2019-07-15 14:33
Thank you for the info, that really helps! 

Yes, it seems to be a problem with URL resolution. We are going to release a new version of the plugin that should fix your case. I will let you know whenever the release is done so you can test with latest release and verify if everything works as expected. 

Regards

**Comment by facsiaginsa** [comment] 2019-07-15 15:27
Thank you very much! 

Oh ya, one more thing, whenever i play the content using vlc, i get around 2mbps download throughput. But when i test it with the plugin for 2 user paralel i only get less than 100kbps, it should be around 4 mbps right? Is this plugin designed like that? or this is another problem?

**Comment by rabelenda** [comment] 2019-07-15 16:46
It might be an issue with plugin reported sample results, when we do the release please re verify this case (since we are including many fixes) and if you find it still doesn't match, open a new ticket for that.

Regards

**Comment by facsiaginsa** [comment] 2019-07-16 01:33
nice to hear that. hope to see the update really soon 👍

**Comment by rabelenda** [comment] 2020-03-01 23:46
Closing since this should have been fixed with release 2.0

**Closed** 2020-03-01 23:45 UTC
